### ISSUE TITLE
HardFault 

### ISSUE THREAD

**Issue by dtony** [maxgerhardt/pio-lorawan-example#1]
I tried this example using PlatformIO under VSCode with the DISCO L072Z LRWAN1 Board from ST and it makes an hard fault when trying to send the join message. Here is the debug trace : 
```
[DBG ][LSTK]: Initializing MAC layer

 Mbed LoRaWANStack initialized

 CONFIRMED message retries : 3

 Adaptive data  rate (ADR) - Enabled
[DBG ][LSTK]: Initiating OTAA
[DBG ][LSTK]: Sending Join Request ...

++ MbedOS Fault Handler ++

FaultType: HardFault

Context:
R0   : 00000029
R1   : 00000002
R2   : 20000EF4
R3   : 00000002
R4   : 20002878
R5   : 00000029
R6   : 3764F508
R7   : 00000001
R8   : 00000000
R9   : 00000000
R10  : 00000000
R11  : 00000000
R12  : 00000000
SP   : 20002D58
LR   : 080091B3
PC   : 08008F5A
xPSR : 01000000
PSP  : 20002D38
MSP  : 20004FC0
CPUID: 410CC601
Mode : Thread
Priv : Privileged
Stack: PSP

-- MbedOS Fault Handler --



++ MbedOS Error Info ++
Error Status: 0x80FF013D Code: 317 Module: 255
Error Message: Fault exception
Location: 0x800032B
Error Value: 0x8008F5A
Current Thread: main  Id: 0x2000106C Entry: 0x800A047 StackSize: 0x400 StackMem: 0x20002AD8 SP: 0x20004F44
For more info, visit: https://mbed.com/s/error?error=0x80FF013D&tgt=DISCO_L072CZ_LRWAN1
-- MbedOS Error Info --
```
It works using online Mbed IDE, any idea what could be wrong ?

**Comment by maxgerhardt** [comment]
Sorry for the extremely late reply. Per https://github.com/ARMmbed/mbed-os-example-lorawan/issues?q=is%3Aissue+HardFault I also see a lot of issues regarding HardFault -- one issue says it was solved by an [mbed-os update](https://github.com/ARMmbed/mbed-os-example-lorawan/issues/93#issuecomment-413419366).

This example was updated to the latest version that PlatformIO supports (mbed-os 6.6.0), plus more documentation was added. Please re-open if the issue is still occuring there.
